### PR TITLE
Fix marketplaceordering issues

### LINKED ISSUE #825: Redundant help entry in _help.py when command group customized
Readme: https://github.com/Azure/azure-rest-api-specs/pull/12484/files#diff-b6e0550bd3822e6a61ceaf441004319d392dc9c5ca8fcf4dc872d0d0eb71e2f0
In readme, command group `marketplaceordering` is renamed to `term`.

While generated _help.py has a redundant help entry for marketplaceordering still : https://github.com/Azure/azure-cli/pull/17686/files#diff-5119c92793d18e9588efeb831bdc955f9d2b4493269da65a32b5898af8128d5fR15. Need to remove it.

### PR DESCRIPTION
**Pull request by qiaozha**
fix #825 
     #833 
     #832

### CODE REVIEW

**Review by changlong-liu — APPROVED** [review]

File: src/generate/renders/CliTopInit.ts [hunk 1]
```diff
@@ -56,7 +62,14 @@ export class CliTopInit extends TemplateBase {
 
                 let loadtableIndex = -1;
                 let loadargIndex = -1;
+                let loadHelpInddex = -1;
```
Comment (lirenhe) [inline src/generate/renders/CliTopInit.ts:65]: typo?

Comment (qiaozha) [reply src/generate/renders/CliTopInit.ts]: changed.
